# GitHub Action for generating a contribution graph with a snake eating your contributions.
name: Generate Snake

on:
  schedule:
    - cron: "0 */12 * * *" # Runs every 12 hours
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v3
    
      - name: Generate the snake files in './dist/'
        uses: Platane/snk@v3
        id: snake-gif
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-contribution-grid-snake.svg?color_snake=#00FF7F&color_dots=#118B50&color_background=#2F3C7E
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark&color_snake=#32CD32&color_dots=#118B50&color_background=#2F3C7E
            dist/github-contribution-grid-snake.gif?color_snake=#20B2AA&color_dots=#118B50&color_background=#2F3C7E
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Show build status
        run: git status

      - name: Push new files to the output branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
          commit_message: "Update snake animations (Auto-generated)"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
